---
#- name: Add new VM to Tower Inventory
#  awx.awx.host:
#  tower_host:
#    name: "{{ vm_hostname }}"
#    inventory: "{{ tower_inventory_name }}"
#    state: present
#    tower_verify_ssl: no
#    variables: |+
#      ---
#      ansible_host: "{{ vm_ip }}"
- name: Add an inventory source
  inventory_source:
    name: "{{ vm_hostname }}"
    inventory: "{{ tower_inventory_name }}"
    state: present
    tower_verify_ssl: no
    variables: |+
      ---
      ansible_host: "{{ vm_ip }}"
 
  
