---
#- name: Add an inventory source
#  inventory:
#    name: "{{ vm_hostname }}"
#    inventory: "{{ tower_inventory_name }}"
#    state: present
#    tower_verify_ssl: no
#    variables: |+
#      ---
#      ansible_host: "{{ vm_ip }}"

- name: Add new VM to Tower Inventory
  tower_host:
    name: "{{ vm_hostname }}"
    inventory: "{{ tower_inventory_name }}"
    state: present
    #tower_verify_ssl: no
    controller_config_file: "~/tower_cli.cfg"
    variables:
      ansible_host: "{{ vm_ip }}"

#- name: Add host
#  host:
#    name: localhost
#    description: "Local Host Group"
#    inventory: "Local Inventory"
#    state: present
#    controller_config_file: "~/tower_cli.cfg"
#    variables:
#      example_var: 123
